services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://vladislav:your_secret_key_here@db:5432/my_first_project_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: vladislav
      POSTGRES_PASSWORD: your_secret_key_here
      POSTGRES_DB: my_first_project_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vladislav -d my_first_project_db" ]
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: todo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  db_data:
  redis_data: